name: setup_node_pnpm_and_corepack
description: Setup Node and install Pnpm and corepack
inputs:
  node-version:
    required: false
    description: The version of Node to use.
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: streetsidesoftware/actions/public/setup-node-pnpm@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable Corepack
      run: |
        corepack enable
        pnpm -v
      shell: bash
