enableGlobDot: true
ignorePaths:
  - .git/{index,config}
  - .git/*/**
  - .gitignore
  - .prettierignore
  - node_modules
  - pnpm-lock.yaml
  - '**/out/**'
  - '**/action-build/**'
  - temp
words:
  - outfile
