name: read-file
description: Read a file and return the contents.

inputs:
  path:
    description: The path to the file to read. The path is relative to the root of the repository.
    required: true
outputs:
  result:
    description: The contents of the file.
    value: ${{ steps.read-file.outputs.result }}
runs:
  using: composite
  steps:
    - name: Read File
      id: read-file
      uses: actions/github-script@v7
      env:
        INPUT_PATH: ${{ inputs.path }}
      with:
        result-encoding: string
        script: |
          const fs = require('fs');
          const path = require('path');
          return fs.readFileSync(path.resolve(process.env.GITHUB_WORKSPACE, process.env.INPUT_PATH), 'utf8');
