name: github_app_token
description: Create a token for making Pull Requests

# Note: this just calls actions/create-github-app-token, but it allows us to keep it in one place.

inputs:
  app_id:
    description: Application ID used to make the PR
    required: true
  app_private_key:
    description: Application Private Key used to sign the PR
    required: true
outputs:
  token:
    description: A token for making Pull Requests
    value: ${{ steps.generate-token.outputs.token }}
runs:
  using: composite
  steps:
    - id: generate-token
      uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 #v2.2.0
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}
