name: setup_node
description: Setup Node and install Pnpm
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '20.x'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
