name: setup_node
description: Setup Node and install Pnpm
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '20.x'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
