name: Example Summary

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - name: Test Step Output
        id: my_step
        uses: streetsidesoftware/actions/.github/actions/output@v1
        with:
          value: |
            Action: ${{ github.action }}
            Actor: ${{ github.actor }}

      - name: Summary
        uses: streetsidesoftware/actions/.github/actions/summary@v1
        with:
          text: |
            # Summary
            Node: `${{ matrix.version }}
            Output: ${{ steps.my_step.outputs.value }}
