name: '📗 Example Dirty'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dirty 1
        id: dirty_1
        uses: streetsidesoftware/actions/public/dirty@v1

      - name: Touch
        run: |
          touch test.txt
          echo "\n make dirty \n" >> README.md

      - name: Dirty 2
        id: dirty_2
        uses: streetsidesoftware/actions/public/dirty@v1

      - name: Summary
        uses: streetsidesoftware/actions/public/summary@v1
        with:
          text: |
            # Dirty Summary

            ## Dirty 1

            isDirty: `${{ steps.dirty_1.outputs.isDirty }}` = ${{ steps.dirty_1.outputs.isDirty && 'Yes' || 'No' }} = ${{ !!steps.dirty_1.outputs.isDirty }}
            status:
            ```
            ${{ steps.dirty_1.outputs.status }}
            ```

            ## Dirty 2

            isDirty: `${{ steps.dirty_2.outputs.isDirty }}` = ${{ steps.dirty_2.outputs.isDirty && 'Yes' || 'No' }} = ${{ !!steps.dirty_2.outputs.isDirty }}
            status:
            ```
            ${{ steps.dirty_2.outputs.status }}
            ```
