name: ' 🧪 Test Build'

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./public/setup-node-pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: |
          pnpm build
          pnpm lint

  validate-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Validate workflows
        # cspell:ignore dsanders
        uses: dsanders11/json-schema-validate-action@v2.0.0
        with:
          schema: https://www.schemastore.org/github-action.json
          files: |-
            .github/actions/*/action.yml
            .github/actions/*/action.yaml
            public/*/action.yml
            public/*/action.yaml
